# Generated by Django 5.1.2 on 2024-11-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
