# Generated by Django 5.1.2 on 2024-12-09 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('credit', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('available', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open'), ('WAITLIST', 'Waitlist')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('courses', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
    ]
