# Generated by Django 5.1.2 on 2024-12-09 23:30

from django.db import migrations, models

#here with every other migration file 
class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('WAITLIST', 'Waitlist'), ('OPEN', 'Open')], max_length=255),
        ),
    ]
