# Generated by Django 5.1.2 on 2024-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('WAITLIST', 'Waitlist')], max_length=255),
        ),
    ]
