# Generated by Django 5.1.2 on 2024-12-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('WAITLIST', 'Waitlist'), ('CLOSED', 'Closed'), ('OPEN', 'Open')], max_length=255),
        ),
    ]
