# Generated by Django 5.1.2 on 2024-12-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITLIST', 'Waitlist'), ('CLOSED', 'Closed')], max_length=255),
        ),
    ]
