# Generated by Django 5.1.2 on 2024-12-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_remove_module_instructors_alter_module_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enrolled_students',
        ),
    ]
