# Generated by Django 5.1.2 on 2024-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_alter_module_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('WAITLIST', 'Waitlist'), ('OPEN', 'Open')], max_length=255),
        ),
    ]
