# Generated by Django 5.1.2 on 2025-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
        ('modules', '0020_alter_module_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='linked_courses', to='modules.module'),
        ),
    ]
