# Generated by Django 5.1.2 on 2025-01-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
    ]
