# Generated by Django 5.1.2 on 2025-01-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_alter_module_available'),
        ('registrations', '0002_alter_registration_date'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'module')},
        ),
    ]
