# Generated by Django 5.1.2 on 2024-11-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_module_student_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='module',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
